# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

monitor=,preferred,auto,auto
monitor=HDMI-A-1,2560x1080@74.99Hz,auto,auto #main monitor config

# This is an additional key binding
#$mainMod = SUPER
#$menu = rofi -show
$terminal = kitty

exec-once = $terminal
exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE  #hyprshade conf
exec-once = nmcli radio wifi on && nmcli connection up ZXL 1 # Auto connect to internet

exec-once = fcitx5 -d # Fcitx5 + Mozc config

exec = hyprshade auto

#bind = $mainMod, SPACE, exec, $menu
#bind = $mainMod, M, exit,
bind = Ctrl_l Alt_l, T, exec, $terminal bashtop
bind = Ctrl_l Alt_l, 9,  exec, hyprshade auto && notify-send "Exec HyprShade" #This bind will exec the hyprshade, use him if hyprshade is not working or when you change the hyprshade.toml.

# These binds will take a shot of the screen
bind = , print, exec, hyprshot -m window 
bind = shift, print, exec, hyprshot -m region

# Change the audio output
bind = Ctrl_l Shift_l, 1, exec, pactl set-default-sink alsa_output.pci-0000_30_00.1.hdmi-stereo && notify-send "Saída de áudio: Monitor"
bind = Ctrl_l Shift_l, 2, exec, pactl set-default-sink alsa_output.usb-Sony_Interactive_Entertainment_Wireless_Headset-00.analog-stereo && notify-send "Saída de áudio: Fone Wireless"

#Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# SDL version
env = SDL_VIDEODRIVER,wayland
# env = SDL_VIDEODRIVER,x11

# No Hardware Cursor
# cursor {
#     no_hardware_cursors = false
# }

# Blur for waybar
#layerrule = blur, waybar

general {
    border_size = 1
}

decoration {
    active_opacity = 0.95
    inactive_opacity = 0.85

    blur {
        enabled = true
        xray = true
        special = false
        new_optimizations = true
        size = 10
        passes = 3
        brightness = 1
        noise = 0.05
        contrast = 0.89
        vibrancy = 0.5
        vibrancy_darkness = 0.5
        popups = false
        popups_ignorealpha = 0.6
        input_methods = true
        input_methods_ignorealpha = 0.8
    }
}

input {
    kb_layout = br
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

     tablet {
        left_handed = true
    }

    touchpad {
        natural_scroll = false
    }
}

# Fcitx5 + Mozc config

env = GTK_IM_MODULE, fcitx5
env = QT_IM_MODULE, fcitx5
env = XMODIFIERS, @im=fcitx5
