-- Put general config stuff here
-- Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1080@74.99Hz",
    position = "auto",
    scale = "auto",
})

-- This is an additional key binding
--$mainMod = SUPER
--$menu = rofi -show
local terminal = "kitty"

--exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE  #hyprshade conf

-- Configuração para o ActivityWatch
-- Servidor principal limpa e inicia o log

-- Watcher unificado do Wayland (Janelas + AFK) adiciona seus logs

--exec = hyprshade auto
-- Verifica o horário ao iniciar. Se for entre 19h e 07h, liga o shader.

--bind = $mainMod, SPACE, exec, $menu
--bind = $mainMod, M, exit,
hl.bind("CTRL + Alt_l + T", hl.dsp.exec_cmd(terminal .. " bashtop"))
hl.bind("CTRL + Alt_l + 9", hl.dsp.exec_cmd("hyprshade auto && notify-send \"Exec HyprShade\""))

-- These binds will take a shot of the screen
hl.bind("print", hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind("SHIFT + print", hl.dsp.exec_cmd("hyprshot -m region"))

-- Change the audio output
hl.bind("CTRL + Shift_l + 1", hl.dsp.exec_cmd("pactl set-default-sink alsa_output.pci-0000_30_00.1.hdmi-stereo && notify-send \"Saída de áudio: Monitor\""))
hl.bind("CTRL + Shift_l + 2", hl.dsp.exec_cmd("pactl set-default-sink alsa_output.usb-Sony_Interactive_Entertainment_Wireless_Headset-00.analog-stereo && notify-send \"Saída de áudio: Fone Wireless\""))

--Example for xwayland
-- xwayland {
--   force_zero_scaling = true
-- }

-- qt5ct environment variable
-- env = QT_QPA_PLATFORMTHEME,qt5ct

-- SDL version
hl.env("SDL_VIDEODRIVER", "wayland")
-- env = SDL_VIDEODRIVER,x11

-- No Hardware Cursor
-- cursor {
--     no_hardware_cursors = false
-- }

-- Blur for waybar
--layerrule = blur, waybar

hl.env("GTK_IM_MODULE", "fcitx")
hl.env("QT_IM_MODULE", "fcitx")
hl.env("XMODIFIERS", "@im=fcitx")
hl.config({
    general = {
        border_size = 1,
    },
    decoration = {
        active_opacity = 0.95,
        inactive_opacity = 0.85,
        blur = {
            enabled = true,
            xray = true,
            special = false,
            new_optimizations = true,
            size = 10,
            passes = 3,
            brightness = 1,
            noise = 0.05,
            contrast = 0.89,
            vibrancy = 0.5,
            vibrancy_darkness = 0.5,
            popups = false,
            popups_ignorealpha = 0.6,
            input_methods = true,
            input_methods_ignorealpha = 0.8,
        },
    },
    input = {
        kb_layout = "br",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        tablet = {
            left_handed = true,
        },
        touchpad = {
            natural_scroll = false,
        },
    },
    -- Fcitx5 + Mozc config
})

hl.on("hyprland.start", function()
    hl.exec_cmd(terminal)
    hl.exec_cmd("dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE")
    hl.exec_cmd("nmcli radio wifi on && nmcli connection up ZXL 1")
    hl.exec_cmd("/opt/activitywatch/aw-server/aw-server > ~/.aw-server.log 2>&1")
    hl.exec_cmd("aw-awatcher >> ~/.aw-server.log 2>&1")
    hl.exec_cmd("fcitx5 -d")
    hl.exec_cmd("hyprshade auto")
    --hl.exec_cmd("fish -c \"set hora (date +%H); if test \\$hora -ge 19 -o \\$hora -lt 07; hyprctl keyword decoration:screen_shader '~/.config/hypr/shaders/blue-light-filter.glsl'; end\"")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("hyprshade auto")
end)

